using System.IO;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using QuestPDF.Drawing;
using QuestPDF.Elements;
using QuestPDF.Previewer;

namespace NXM.Tensai.Back.OKR.AI.Services
{
    public class PdfGeneratorService
    {
        public byte[] GeneratePdfFromText(string title, string content)
        {
            QuestPDF.Settings.License = QuestPDF.Infrastructure.LicenseType.Community;
            // Use QuestPDF to generate a visually appealing PDF
            return QuestPDF.Fluent.Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);
                    page.Size(PageSizes.A4);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(12).FontFamily("Arial"));

                    page.Header().Element(header =>
                    {
                        header.Row(row =>
                        {
                            row.RelativeItem().Column(col =>
                            {
                                col.Item().PaddingBottom(10).Text(title ?? "Document")
                                    .FontSize(22)
                                    .Bold()
                                    .FontColor(Colors.Blue.Medium);
                                col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                            });
                        });
                    });

                    page.Content().PaddingVertical(20).Element(body =>
                    {
                        body.Column(col =>
                        {
                            col.Item().Text(content ?? string.Empty)
                                .FontSize(13)
                                .FontColor(Colors.Grey.Darken3)
                                .LineHeight(1.5f);
                        });
                    });

                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by Tensai OKR System").FontSize(10).FontColor(Colors.Grey.Medium);
                    });
                });
            }).GeneratePdf();
        }
    }
}
